<?php

namespace Paprec\CatalogBundle\Repository;

/**
 * ArgumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArgumentRepository extends \Doctrine\ORM\EntityRepository
{
}
