<?php

namespace Paprec\CatalogBundle\Repository;

/**
 * CustomizableAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomizableAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
