<?php

namespace Paprec\CatalogBundle\Repository;

/**
 * CustomAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
