<?php

namespace Paprec\CatalogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostalCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostalCodeRepository extends EntityRepository
{
    public function findLikeByCode($query)
    {
        $queryBuilder = $this
            ->createQueryBuilder('p')
            ->where('p.code LIKE :code')
            ->andWhere('p.deleted IS NULL')
            ->setParameter('code', $query.'%')
            ->orderBy('p.code', 'ASC')
        ;

        return $queryBuilder->getQuery()->getResult();
    }
}
