<?php

namespace Paprec\CatalogBundle\Repository;

/**
 * PriceListLineD3ERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceListLineD3ERepository extends \Doctrine\ORM\EntityRepository
{
}
