<?php

namespace Paprec\CatalogBundle\Repository;

/**
 * ProductChantierCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductChantierCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
