<?php

namespace Paprec\CatalogBundle\Repository;

/**
 * ProductDIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDIRepository extends \Doctrine\ORM\EntityRepository
{
}
