<?php

namespace Paprec\CatalogBundle\Repository;

/**
 * ProductDICategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDICategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
