<?php

namespace Paprec\CatalogBundle\Repository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductD3ETypeRepository extends \Doctrine\ORM\EntityRepository
{
}
