<?php

namespace Paprec\CatalogBundle\Repository;

/**
 * ProductChantierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductChantierRepository extends \Doctrine\ORM\EntityRepository
{
}
