<?php

namespace Paprec\HomeBundle\Repository;

/**
 * TicketFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketFileRepository extends \Doctrine\ORM\EntityRepository
{
}
