<?php

namespace Paprec\HomeBundle\Repository;

/**
 * TicketMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
