<?php

namespace Paprec\CommercialBundle\Repository;

/**
 * BusinessLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessLineRepository extends \Doctrine\ORM\EntityRepository
{
}
