<?php

namespace Paprec\CommercialBundle\Repository;

/**
 * ProductD3EQuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductD3EQuoteRepository extends \Doctrine\ORM\EntityRepository
{
}
