<?php

namespace Paprec\CommercialBundle\Repository;

/**
 * ProductD3EQuoteLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductD3EQuoteLineRepository extends \Doctrine\ORM\EntityRepository
{
}
