<?php

namespace Paprec\CommercialBundle\Repository;

/**
 * ProductDIQuoteLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDIQuoteLineRepository extends \Doctrine\ORM\EntityRepository
{
}
