<?php

namespace Paprec\CommercialBundle\Repository;

/**
 * ProductChantierQuoteLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductChantierQuoteLineRepository extends \Doctrine\ORM\EntityRepository
{
}
