<?php

namespace Paprec\CommercialBundle\Repository;

/**
 * ProductChantierOrderLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductD3EOrderLineRepository extends \Doctrine\ORM\EntityRepository
{
}
