<?php

namespace Paprec\CommercialBundle\Repository;

/**
 * ProductChantierOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductChantierOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
