<?php

namespace Paprec\CommercialBundle\Repository;

/**
 * ProductDIQuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDIQuoteRepository extends \Doctrine\ORM\EntityRepository
{
}
