<?php

namespace Paprec\CommercialBundle\Repository;

/**
 * ProductChantierQuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductChantierQuoteRepository extends \Doctrine\ORM\EntityRepository
{
}
