<?php

namespace Paprec\CommercialBundle\Repository;

/**
 * QuoteRequestLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteRequestLineRepository extends \Doctrine\ORM\EntityRepository
{
}
