<?php

namespace Paprec\CommercialBundle\Repository;

/**
 * QuoteRequestNonCorporateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteRequestNonCorporateRepository extends \Doctrine\ORM\EntityRepository
{
}
