<?php

namespace Paprec\CommercialBundle\Repository;

/**
 * QuoteRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
